# Generated by Django 5.1.1 on 2024-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.FloatField(verbose_name=10)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animais'},
        ),
    ]
