# Generated by Django 5.1.1 on 2024-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_animal_peso_alter_tutor_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='raca',
        ),
    ]
