# Generated by Django 5.1.1 on 2024-10-06 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_raca_remove_animal_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.animal')),
                ('porte', models.CharField(max_length=50)),
            ],
            bases=('aplic.animal',),
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.animal')),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
            bases=('aplic.animal',),
        ),
        migrations.DeleteModel(
            name='raca',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
    ]
