# Generated by Django 5.1.1 on 2024-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_cachorro_gato_delete_raca_alter_animal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachorro',
            options={'verbose_name_plural': 'Cachorros'},
        ),
        migrations.AlterModelOptions(
            name='gato',
            options={'verbose_name_plural': 'Gatos'},
        ),
    ]
