# Generated by Django 5.1.1 on 2024-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_alter_cachorro_options_alter_gato_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
